### ISSUE TITLE
Games may overlap if they don't fall on the same timeslot exactly

### ISSUE THREAD

**Issue by joshuarpearce** [bobrippling/lunchbot#6]
https://github.com/bobrippling/lunchbot/blob/0e898f5fe8a21495a2fc230ac06d449b0bd729c4/PS4Bot.py#L118

This allows a game to start at 2:30 and somebody can schedule one at 2:10 without a conflict. Should be done as a datetime comparison against the two times instead.

**Comment by bobrippling** [comment]
Fear not - sorted it. Bug was introduced here bfa52bb1dfdbfe98d0094eb6bd142fb44d4664fc and fixed here b4711c3b847880b5540239f1eff9a250c787f131
